### PR TITLE
chore: Uses specific lodash methods

### PR DESCRIPTION
**Pull request by mathewmorris**
In reference to #88 

This should only pull in certain methods needed from lodash instead of the entire library.

### CODE REVIEW

**Comment by erikshestopal** [comment]
@mathewmorris does webpack not tree shake all the code that's not used?

**Comment by mathewmorris** [comment]
> @mathewmorris does webpack not tree shake all the code that's not used?

I believe molekule uses babel to build. So, I'm not sure that babel actually treeshakes outside of it's own methods from core-js and other plugins.

**Comment by mathewmorris** [comment]
Though, Rollup might do the treeshaking for us. I'll confirm. I'll also analyze the bundles for some concrete evidence.

**Comment by mathewmorris** [comment]
Ah. Rollup is not being used in the build process.

**Comment by mathewmorris** [comment]
@erikshestopal Yeah, so babel is just compiling everything into the lib folder. Nothing is being bundled.

**Pull request merged**
