### PR TITLE
feat: Update styled-components version

### PR DESCRIPTION
**Pull request by mosvov**
### 📃 Summary

Update styled-components version to prevent class name override
### 🏷 Asana Task
https://app.asana.com/0/1163858713826545/1194726063398491/f
### 📈 Risk Analysis
- [ ] Does this affect patients?
- [ ] Does this affect clinical?
- [ ] Does this mutate data?
- [ ] Does it touch PHI?
- [ ] Does it touch payments?
- [ ] Does it update Node packages?

### CODE REVIEW

**Comment by alextranwork** [comment]
This codebase is in the process of being merged into another repo: https://github.com/heydoctor/singularity/pull/61

**Comment by mosvov** [comment]
I will create another PR into `singularity` after that merge

**Comment by alextranwork** [comment]
looks like there was a UI change, can you look at the chromatic checks and confirm

**Comment by alextranwork** [comment]
Does the new version fix anything in particular?

**Comment by mosvov** [comment]
No, just to consolidate versions across repo

**Pull request closed without merging**
