### PR TITLE
feat: add boxed checkbox styling

### PR DESCRIPTION
**Pull request by gerrymi**
## 📃 Summary
Added a boolean prop to enable boxed styling, along with a width prop.
boxed-checkbox

### 🏷 Asana Task
https://app.asana.com/0/1179589169762852/1188967808291211/f
	
### 📈 Risk Analysis
- [ ] Does this affect patients?
- [ ] Does this affect clinical?
- [ ] Does this mutate data?
- [ ] Does it touch PHI?
- [ ] Does it touch payments?
- [ ] Does it update Node packages?

### CODE REVIEW

**Comment by vietnogigoodrx** [comment]
I am thinking this checkbox design should not live in molekule because its not used for the webapp.

**Comment by vietnogigoodrx** [comment]
Can we confirm with the design team that they are planning to have the same checkbox design in the webapp too?

**Comment by gerrymi** [comment]
@vietnogigoodrx Waiting on design to get back to me on that, although I don't necessarily agree that only designs used in both apps warrant being included in molekule... I think if something is more than a one off that doesn't affect other functionality, it should be able to live in molekule.

**Comment by vietnogigoodrx** [comment]
@gerrymi My concern is that Molekule is suppose to be the base component. This PR appears to be adding a customization to the base design which is breaking our philosophy.

**Comment by gerrymi** [comment]
@vietnogigoodrx if that's the case then it doesn't matter if web-app implements it because it's not considered "base" design.

**Pull request closed without merging**
